version: '3.8'

services:
  db:
    image: postgres
    container_name: jenkins-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jenkins
    ports:
      - "5434:5432"
    volumes:
      - /Users/mallikaroy/gitlearn/spring-kenkins-volume:/var/lib/postgresql/data
  app:
    build: .
    image: jenkins-app
    container_name: jenkins-app-cont
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jenkins
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
